# Site settings
title: Derek's Website 
description: This is my Data Analytics Website. 
url: "https://dgraves4.github.io/cintel-01-pages/"

# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one  
